### ISSUE TITLE
ADC07 doesn't work properly 

### ISSUE THREAD

**Issue by oleksiybond** [microdaq/Scilab#35]
Hello! 

On MicroDAQ E2000 it appeared that ADC07 doesn't work properly - no data (even no zeroes) from the analog input. Tested with  "Analog Loop Demo". In differential mode, however, some meaningless data appear. The DAC outputs correct data (checked with an oscilloscope). 

mdaqLog info:

Log generated on: 26-Dec-2017
Toolbox ver: 1.2.0

---- MLink log:
-----------------------------------
   MicroDAQ E2000-ADC07-DAC04-10
-----------------------------------
Hardware configuration:
	CPU: 456MHz
	Storage: 4GB
	Analog inputs (AI): 8 channel, 1000ksps, 16-bit, ±10.24V | ±5.12V | ±2.56V | ±1.28V | ±0.64V range
	Analog outputs (AO):  16 channel, 12-bit, ±10V | ±5V | ±2.5V | 0-10V | 0-5V range
	Digital input/output (DIO): 16 channels, 5V/TTL
IP settings:
	IP address: 172.17.5.197
Firmware version:
	2.0.1 (build: 16)

---- Scilab environment info:
Scilab architecture: x64
Scilab Version:  5.5.3.1435912166
Operating System:  Windows 7 6.1
Java version:  1.6.0_41
Java runtime information:  Java(TM) SE Runtime Environment (build 1.6.0_41-b02)
Java Virtual Machine information:  Java HotSpot(TM) 64-Bit Server VM (build 20.14-b01, mixed mode)
Vendor specification:  Sun Microsystems Inc.

**Comment by embedded-solutions** [comment]
Is mdaqAIRead() from Scilab console works ?

mdaqAIRead(1, [-10.24 10.24], f%)

**Comment by oleksiybond** [comment]
Well, actually I can't check it for the moment because I ran into a different problem:

I remember that it was working Ok with the past version of firmware, so in pursuing the goal of testing I "downgraded" the firmware and when the process was "finished" I found a small note that downgrade is not the same as upgrade :-( 
So I need the instruction first how to upgrade back to 2.0.0 firmware.

**Comment by embedded-solutions** [comment]
I will test your configuration and contact you on Thursday to fix this problem. Sorry for inconvenience.

**Comment by oleksiybond** [comment]
Hello! Is there any solution to my problem?

**Comment by embedded-solutions** [comment]
We are working on it. We have found the issue and is fixed, we need 2 more days to perform some test and build new release. By the end of this week we will provide upgrade package.

**Comment by embedded-solutions** [comment]
Please try to use attached file. Files contain fix for the issue with ADC7 rev0, this fix will be included in 1.2.1v release. 

Please download, unpack and copy lib files to MicroDAQ toolbox directory containing DSP libraries. In order to obtain directory path you can use the following command: 

pathconvert(mdaqToolboxPath() + 'etc/mdaqlib')

Please let us know if this solves your problem. Sorry for inconvenience. 


[adc7-rev0--hot-fix-scilab.zip](https://github.com/microdaq/Scilab/files/1649009/adc7-rev0--hot-fix-scilab.zip)

**Comment by oleksiybond** [comment]
Thank you for the patch. I would try it at the earliest convenience, but as I mentioned before, due to erroneous firmware downgrade, the device is now out of order - after plugging in the power the both LED continue to be on, and usb device is not recognized on linux or windows either. So, before I can try the patch I need to know how to load the latest firmware.

**Comment by oleksiybond** [comment]
Ok, I have restored the operability of the device and checked the patch.
At least some data appear from AI channel but it is wrong data. (for test I used ext_analog_demo)
![ext_analog_demo](https://user-images.githubusercontent.com/34851093/35315732-57d1dba4-0111-11e8-85f0-fe351c6de359.png)

[mdaqLog.txt](https://github.com/microdaq/Scilab/files/1658681/mdaqLog.txt)

**Comment by oleksiybond** [comment]
I have tried also direct hardware access with mdaqAIScan with no result.
