### ISSUE TITLE
Can't see Microdaq toolbox in palette

### ISSUE THREAD

**Issue by rtarb41323** [microdaq/Scilab#43]
When I start Scilab 5.5.2, I see the Microdaq toolbox  load:

- Done
	Load demos

Start MicroDAQ toolbox ver: 1.2.1
	Load macros
	Load demos
	Load help
	Load MLink library
	Load MicroDAQ blocks

 Scanning repository http://atoms.scilab.org/5.5 ... Done

However, when I look at the toolbox palette, I don't see any "Microdaq" toolbox.
![toolbox_load](https://user-images.githubusercontent.com/5414497/43434787-31bfefe6-944b-11e8-9d78-c353a873efd7.png)

**Comment by witczenko** [comment]
When it started happened? Did you have that problem before? 
Maybe some new toolbox cause problem with loading MicroDAQ toolbox. 
Try to unload all other toolboxes and see if something changes.

**Comment by rtarb41323** [comment]
Update: If I manually execute the microdaq file "loader.sce" in Scilab, and then I start xcos, then I DO see the Microdaq toolbox.

**Comment by embedded-solutions** [comment]
Can you please try to disable all other toolboxes and try to load only MicroDAQ toolbox? It is possible that some other toolboxes can affect loading of MicroDAQ toolbox.

**Comment by rtarb41323** [comment]
Update: I can't uninstall/reinstall any toolboxes at the moment, because my ATOMS module is broken.
"NO ATOMS module is available.  Please, check your Internet connection or make sure that your OS is compatible with ATOMS".

--> I understand that this has nothing to do with the Microdaq toolbox itself.  I must first unmess my ATOMS package.

**Comment by embedded-solutions** [comment]
Yes, currently ATOMS system is not working correctly. In order to install MicroDAQ toolbox on Scilab 5.5.2 you can use following script which workarounds install Atoms issue. 

getURL("www.microdaq.org/scilab/toolbox/mdaqInstallLatestToolbox.sce");
exec("mdaqInstallLatestToolbox.sce");

**Comment by rtarb41323** [comment]
After uninstalling Scilab, and then re-installing the Microdaq toolbox with the above commands
(repeated here:)

getURL("www.microdaq.org/scilab/toolbox/mdaqInstallLatestToolbox.sce");
exec("mdaqInstallLatestToolbox.sce");

The toolbox is now working fine.  Thank you for your help!
